Support for GNOME 3.8 (see note)
NOTE: Extension works now as expected but a button in notifications had to be
disabled due to a bug in gnome-shell.

Stack trace:
JS ERROR: !!!   Exception was: TypeError: string.substr is not a function
JS ERROR: !!!     message = '"string.substr is not a function"'
JS ERROR: !!!     fileName = '"/usr/share/gnome-shell/js/ui/messageTray.js"'
JS ERROR: !!!     lineNumber = '224'
JS ERROR: !!!     stack = '"strHasSuffix@/usr/share/gnome-shell/js/ui/messageTray.js:224
Notification<.addButton@/usr/share/gnome-shell/js/ui/messageTray.js:698
wrapper@/usr/share/gjs-1.0/lang.js:213
PomodoroTimer<._notifyPomodoroEnd@/home/haaja/.local/share/gnome-shell/extensions/pomodoro@arun.codito.in/timer.js:464
wrapper@/usr/share/gjs-1.0/lang.js:213
PomodoroTimer<._onTimeout@/home/haaja/.local/share/gnome-shell/extensions/pomodoro@arun.codito.in/timer.js:364
wrapper@/usr/share/gjs-1.0/lang.js:213